version: '3'

volumes:
  local_mysql_data: {}

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - local_mysql_data:/var/lib/mysql:Z
    env_file:
      - ./.envs/.mysql
    environment:
      MYSQL_ROOT_PASSWORD: aid
      MYSQL_USER: aid
      MYSQL_PASSWORD: aid
